name: FunTestGame

options:
  bundleIdPrefix: com.tjadev

  deploymentTarget:
    iOS: "15.0"

targets:

  FunTestGame:
    type: application
    platform: iOS

    sources:
      - FunTestGame.swift

    info:
      path: Info.plist

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tjadev.FunTestGame
        PRODUCT_NAME: FunTestGame

        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"

        TARGETED_DEVICE_FAMILY: "1"

        GENERATE_INFOPLIST_FILE: NO

        INFOPLIST_KEY_UIRequiresFullScreen: YES

      configs:

        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"

        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
